### ISSUE TITLE
Возможно нарушена структура документа

### ISSUE THREAD

**Issue by az09** [baltti/gis-itmo#2]
https://github.com/baltti/gis-itmo/blob/aba1f1057d4e76b245bc90e5a4357746d1ee72a1/02-basics.Rmd#L225
Этот подзаголовок и следующий за ним "Параметры листа" расположены на одном уровне иерархии, что создаёт путаницу, будто глава 3.4.2 отсутствует.

**Comment by baltti** [comment]
Спасибо, исправила.
Действительно перепутала немного иерархию заголовков
